
import Navbar from './components/Navbar/navbar'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Devine Techknowlogy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

<body className={inter.className}>
       <Navbar/>
        <main>{children}</main>
       
      </body>
    </html>
  )
}
