<<<<<<< HEAD
// import Navbar from './components/Navbar/navbar'
=======
>>>>>>> e334131118fb4348964e6fd075c9c33892d4f331
import Navbar from './components/Navbar/navbar'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

<body className={inter.className}>
       <Navbar/>
        <main>{children}</main>
       
      </body>
    </html>
  )
}
